//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace monius.Cryptography {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceObjects {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceObjects() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("monius.Cryptography.ResourceObjects", typeof(ResourceObjects).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;Modulus&gt;ygbcnfbCDEIKjXI0uypJUOOueDvJ87vjIa0BiddXRP3rZZ0+u5PCKXBEnR8ASKuYykQuCwE6vGTOJVs1xetiqN7+G5kfQD72RodRMYm1eeec5UEJONqzeVswBjagoebZMAXfkMJaZuM0v8QN9LfekasbMbPqbhwY2+jilH/c1pE=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;/RSAKeyValue&gt;.
        /// </summary>
        internal static string RsaPbKey {
            get {
                return ResourceManager.GetString("RsaPbKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;&lt;Modulus&gt;ygbcnfbCDEIKjXI0uypJUOOueDvJ87vjIa0BiddXRP3rZZ0+u5PCKXBEnR8ASKuYykQuCwE6vGTOJVs1xetiqN7+G5kfQD72RodRMYm1eeec5UEJONqzeVswBjagoebZMAXfkMJaZuM0v8QN9LfekasbMbPqbhwY2+jilH/c1pE=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;P&gt;52rhGtobQJRIXWqtECtjSX7fKjccXxEvSBYT7y6uHutoj17CbxRDKgtC38EHLr/EgTNbdKTaDw3t6dhY+DoDeQ==&lt;/P&gt;&lt;Q&gt;33y85iYU1lKkt6H4hKct6XFWuX71vR9ThwSF/5H13pl9EHAoTEHhClB+XGIXUimutdX5dWSxQzF5kztXDyjN2Q==&lt;/Q&gt;&lt;DP&gt;JZBVxdQNhGgNbwx31x4T2cQ8WU/kzRGvCRZ8WeDL5rzzlgIdsYYqeNKnIkbk8ZOzQ/2gJMj1lGgAbGrv1iskkQ==&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RsaPrKey {
            get {
                return ResourceManager.GetString("RsaPrKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecurityKeyIsNull.
        /// </summary>
        internal static string SecurityKeyIsNull {
            get {
                return ResourceManager.GetString("SecurityKeyIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecurityKeySizeIsNotCorrect.
        /// </summary>
        internal static string SecurityKeySizeIsNotCorrect {
            get {
                return ResourceManager.GetString("SecurityKeySizeIsNotCorrect", resourceCulture);
            }
        }
    }
}
